# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Navigate to the backend directory
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'
#    - name: Change directory to backend
#      run: cd backend
    - name: clean install
      working-directory: backend
      run: npm ci

    - name: build
      working-directory: backend
      run: npm run build --if-present
    
    # Run npm test in the backend directory
    - name: test
      working-directory: backend
      run: npm test

  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }} # Use the desired Node.js version
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Clean install for frontend
      working-directory: frontend
      run: npm ci

    - name: Build frontend
      working-directory: frontend
      run: npm run build --if-present

    - name: Test frontend
      working-directory: frontend
      run: npm test
    
